### ISSUE TITLE
Crash: Comparator placed to read out 

### ISSUE THREAD

**Issue by MrPopannes** [dragon-forge/BotanicAdditions#4] opened 2023-04-25 19:14 UTC
Modpack: FTB Skies 1.0.6

When a vanilla comparator is place down next to the Gaia Agglomeration Plate to read out a possible value (tests for automation) the game crashed.

Crash log:
https://gist.github.com/MrPopannes/f5fdacf1c1e6075a89efd11b34e25239

**Comment by Zeitheron** [comment] 2023-04-25 19:23
Duplicate of #1

**Closed as completed by Zeitheron** 2023-04-25 19:23 UTC
